title: FGG Elbe Datenportal Dokumentation
remote_theme: pmarsceill/just-the-docs

url: https://pegasuswerbeagentur.github.io/elbe-datenportal-doku

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"


# Color scheme supports "light" (default) and "dark"
color_scheme: dark
