title: FGG Elbe Datenportal Dokumentation
remote_theme: pmarsceill/just-the-docs
kramdown:
  auto_ids: false 

url: https://docs.elbe-datenportal.de/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/wappen35hellblau.png"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

color_scheme: light